name: Run tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm set-script prepublish ""
      - run: npm ci
      - run: npm test
      - run: npm run build --if-present